### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by PaganoBerserker** [DECENTRALIZEDCLIMATE/docs#31]
#### **Details:**  The document is of vital importance as it describes important points for the project. In the image, it can be seen that it talks about a Jekyll workshop when the README should be a description of the docs page (Img1)

![Image](https://user-images.githubusercontent.com/47154857/236001547-c52318ab-eccc-4dcd-9f46-d22bcf7a17da.png)
**Img1.- The image shows the error, as it describes a workshop instead of what the docs page is about.**

####  **Proposal solution: How to Create the README for an Open-Source Software Project**

- [x] **Title and Description:** The README should begin with a clear title and a brief description of the project. This will help users understand what your project is all about.

- [x] **System Requirements:** If your project has any system requirements, such as specific versions of software, libraries, or hardware, you should mention it in the README.

- [x] **Installation:** Provide detailed instructions on how to install and set up your project. This should include all necessary steps, such as downloading files, installing dependencies, and configuring environment variables.
- [x] **Usage:** Describe how to use your project. Provide code examples and explain the different options and parameters.

- [x] #32

- [x] **License:** It's important that users know under what license your project is distributed. Include a section that describes the license and the terms of use.

- [x] **Contact:** Provider contact information so that users can reach out to you if they have questions or issues.

> These steps to follow are suggestions provided by ChatGPT and Phind.

**Comment by P1R** [comment]
I will do the contribution section

**Comment by P1R** [comment]
Please add the following section before contribute section:

# HOW TO MAKE A POST

## How to Make a Post in a Jekyll Repository
If you want to publish a post or article on docs.decentralizedclimate.org, follow these steps:

1. Create a markdown file in the following directory if it's for the DCF directory:
```bash
https://github.com/DECENTRALIZEDCLIMATE/docs/tree/develop/_posts/
or in the following directory if it's for social services:
```

```bash
https://github.com/DECENTRALIZEDCLIMATE/docs/tree/develop/_posts/socialserv
```

2. The post must contain the following data:
2.1. A header with the following data in markdown format:

```yaml
---
title: Git & Gitflow Cheetsheet EN
author: Decentralized Climate Foundation
date: 2023-03-15
category: git-flow
layout: post
---
```

2.2. A file name starting with the date in the format YYYY-MM-DD-myposttopic.md. Some examples already exist in the directory.

3. Add a link to the post in the DCF or social services directory by following these steps:
3.1. For the social services directory, go to the following link and paste the markdown of the post under the "Mans & CheetSheets" section in the following format:

```yaml
## Mans & CheetSheets

| Document | Last Update |
| -------- | -------- |
| [Git & GitFlow ES]({% post_url socialserv/2023-03-15-gitflowCheetSheet_ES %}) |  2023-02-16 |
| [Git & GitFlow EN]({% post_url socialserv/2023-03-15-gitflowCheetSheet_EN %}) |  2023-02-16 |
```

3.2. Similarly, for the DCF directory, add a link with these example directives to the following link:

```bash
https://github.com/DECENTRALIZEDCLIMATE/docs/blob/develop/index.md
```

> Note that the URL is not a permalink. It is in the format YYYY-MM-DD-myposttopic without the .md extension.

4. Optional: You can fork the project on your user account on the develop branch and link it to hackmd.io to edit before making a commit to your own repository. Then, submit a pull request, or edit the post directly in the GitHub editor.

5. When your request is accepted on the develop branch, it will appear on the following link:

### [develop branch website](https://develop.docs.decentralizedclimate.org)

6. Additionally, if you want to add images to your post, place them in the assets directory. Please refer to the README.md for more information.

7. If you have any questions, you can convene a meeting or workshop with the board of directors.

**Comment by P1R** [comment]
@PaganoBerserker  is it possible you add the process to decentralize images? I am not usre it is covered in the Contribute/MakePost Section, please add this tool as reference to reduce assets size:
https://squoosh.app/

**Comment by P1R** [comment]
@PaganoBerserker  is it possible you add the process to decentralize images? I am not usre it is covered in the Contribute/MakePost Section, please add this tool as reference to reduce assets size:
https://squoosh.app/
